FROM maven:3.9-eclipse-temurin-21-alpine AS builder
WORKDIR /build
COPY backend /build
RUN mvn clean install -DskipTests -q

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=builder /build/enquiry-service/target/enquiry-service-1.0.0.jar app.jar
EXPOSE 8085
ENTRYPOINT ["java", "-XX:+UseG1GC", "-XX:MaxRAMPercentage=75.0", "-jar", "app.jar"]
